title: My Portfolio
description: Personal portfolio of Rishav
baseurl: ""
url: "https://username.github.io"
theme: cayman@v0.2.0
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
